#!/bin/bash

SERVICE_NAME="laravel-package-dev"

case "$1" in
    composer)
        shift
        docker-compose run --rm $SERVICE_NAME composer "$@"
        ;;
    php)
        shift
        docker-compose run --rm $SERVICE_NAME php "$@"
        ;;
    phpunit)
        shift
        docker-compose run --rm $SERVICE_NAME vendor/bin/phpunit "$@"
        ;;
    rebuild)
        echo "Rebuilding the Docker container..."
        USER_ID=$(id -u)
        GROUP_ID=$(id -g)

        docker-compose build --no-cache \
            --build-arg UID=$USER_ID \
            --build-arg GID=$GROUP_ID
        echo "Rebuild complete."
        ;;
    *)
        echo "Unsupported command. Use one of the following:"
        echo "  ./dev composer [args]   Run Composer commands in the container"
        echo "  ./dev php [args]        Run PHP commands in the container"
        echo "  ./dev rebuild           Rebuild the container"
        ;;
esac
